export const coffees = [
    {
        title: "Expresso Tradicional",
        description: "O tradicional café feito com água quente e grãos moídos",
        price: 9.90,
        tags: ["tradicional"],
        src: "/assets/coffees/expresso.png",
    },
    {
        title: "Expresso Americano",
        description: "Expresso diluído, menos intenso que o tradicional",
        price: 9.90,
        tags: ["tradicional"],
        src: "/assets/coffees/americano.png",
    },
    {
        title: "Expresso Cremoso",
        description: "Café expresso tradicional com espuma cremosa",
        price: 9.90,
        tags: ["tradicional"],
        src: "/assets/coffees/expresso-cremoso.png",
    },
    {
        title: "Expresso Gelado",
        description: "Bebida preparada com café expresso e cubos de gelo",
        price: 9.90,
        tags: ["tradicional", "gelado"],
        src: "/assets/coffees/cafe-gelado.png",
    },
    {
        title: "Café com Leite",
        description: "Meio a meio de expresso tradicional com leite vaporizado",
        price: 9.90,
        tags: ["tradicional", "com leite"],
        src: "/assets/coffees/cafe-com-leite.png",
    },
    {
        title: "Latte",
        description: "Uma dose de café expresso com o dobro de leite e espuma cremosa",
        price: 9.90,
        tags: ["tradicional", "com leite"],
        src: "/assets/coffees/latte.png",
    },
    {
        title: "Capuccino",
        description: "Bebida com canela feita de doses iguais de café, leite e espuma",
        price: 9.90,
        tags: ["tradicional", "com leite"],
        src: "/assets/coffees/capuccino.png",
    },
    {
        title: "Macchiato",
        description: "Café expresso misturado com um pouco de leite quente e espuma",
        price: 9.90,
        tags: ["tradicional", "com leite"],
        src: "/assets/coffees/macchiato.png",
    },
    {
        title: "Mocaccino",
        description: "Café expresso com calda de chocolate, pouco leite e espuma",
        price: 9.90,
        tags: ["tradicional", "com leite"],
        src: "/assets/coffees/mochaccino.png",
    },
    {
        title: "Chocolate Quente",
        description: "Bebida feita com chocolate dissolvido no leite quente e café",
        price: 9.90,
        tags: ["especial", "com leite"],
        src: "/assets/coffees/chocolate-quente.png",
    },
    {
        title: "Cubano",
        description: "Drink gelado de café expresso com rum, creme de leite e hortelã",
        price: 9.90,
        tags: ["especial", "gelado", "acoólico"],
        src: "/assets/coffees/cubano.png",
    },
    {
        title: "Havaiano",
        description: "Bebida adocicada preparada com café e leite de coco",
        price: 9.90,
        tags: ["especial"],
        src: "/assets/coffees/havaiano.png",
    },
    {
        title: "Árabe",
        description: "Bebida preparada com grãos de café árabe e especiarias",
        price: 9.90,
        tags: ["especial"],
        src: "/assets/coffees/arabe.png",
    },
    {
        title: "Irlandês",
        description: "Bebida a base de café, uísque irlandês, açúcar e chantilly",
        price: 9.90,
        tags: ["especial"],
        src: "/assets/coffees/irlandes.png",
    },
]